server:
  port: 9160
spring:
  application:
    name: Share-Service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: investmentdb
  codec:
    max-in-memory-size: 16MB
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost